#!/bin/bash


curl "http://localhost:8080/modules/TextMessageModule" \
-H "Accept: application/json" \
-H "Content-Type:application/json" \
--data @<(cat <<EOF
{
  "content": "$1",
  "style": "$2",
  "class": "$3"
  }
EOF
)
